spring.application.name=CandidateService

server.port=8080

# ===============================
# = DATA SOURCE
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/mydbms?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root@39
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# = JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# = LOGGING
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true


jwt.secret=YBPg/M+Z4L4Wl+SW2wN+K3txv7dJj8R9U9zz37ZEl30=
jwt.expiration-ms=3600000
jwt.issuer=sura-auth
